baseURL = "https://swampcastle.org/"
languageCode = "en-us"
title = "Swamp Castle"

[pygments]
pygmentsuseclasses = false
pygmentsstyle = "vs"
PygmentsCodeFences = true

[blackfriday]
smartypants = false

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"