baseURL = "https://swampcastle.org/"
languageCode = "en-us"
title = "Swamp Castle"

pygmentsCodefences = true
pygmentsStyle = "tango"

[blackfriday]
smartypants = false

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"